### ISSUE TITLE
🐞 Waterfox Issue List Tracker

### ISSUE THREAD

**Issue by Peacock365** [BrowserWorks/waterfox#538]
_Hey there!_

_This is a list of Waterfox bugs yet unresolved. No guarantee for completeness. Should some of them be resolved by now, feel free to inform me. I will delete the corresponding entries in this case. This issue was created in an attempt to create an overview and as a potential starting point for sorting them out._

### Waterfox General
- [ ] Portable updater deleting inappropriately? 
- [ ] Build Waterfox on linux with static musl libc
- [ ] Add README to Linux tarball
- [x] ANGLE -> MoltenVK for macOS
- [ ] Checksum for file downloads
- [ ] Revert Bug 606655
- [ ] libc++ for macOS builds (https://github.com/parrotgeek1/FirefoxLegacy)
- [ ] 1405031 - Support additional click events for browserAction and pageAction
- [ ] https://github.com/MrAlex94/Waterfox/issues/1265
- [ ] https://bugzilla.mozilla.org/show_bug.cgi?id=1373490
- [ ] https://bugzilla.mozilla.org/show_bug.cgi?id=1419264
- [ ] https://bugzilla.mozilla.org/show_bug.cgi?id=1596894
- [ ] https://bugzilla.mozilla.org/show_bug.cgi?id=1419264
- [ ] Re-instate use of [WebCompat](https://github.com/mozilla/gecko-dev/tree/esr60/browser/extensions/webcompat) add-on to help fix website issues, including [UA](https://wiki.mozilla.org/Compatibility/Go_Faster_Addon/Override_Policies_and_Workflows#User_Agent_overrides)!

### Waterfox Classic

- [ ] Waterfox/Mac dictation bug https://github.com/MrAlex94/Waterfox/issues/85
- [ ] On Linux: .config/waterfox | https://github.com/MrAlex94/Waterfox/issues/243 | https://bugzilla.mozilla.org/show_bug.cgi?id=259356
- [ ] Extensions break on path change https://github.com/MrAlex94/Waterfox/issues/329
- [ ] Program description on Windows misleading https://github.com/MrAlex94/Waterfox/issues/387
- [ ] Spellchecking bug https://github.com/MrAlex94/Waterfox/issues/374
- [ ] Autoshortening of hamburger menu fails | https://github.com/MrAlex94/Waterfox/issues/373
| **POSSIBLE SOLUTION**: https://bugzilla.mozilla.org/show_bug.cgi?id=1415921#c0
- [ ] Use unbiased pixelrounding for borders | https://github.com/MrAlex94/Waterfox/issues/422
| **POSSIBLE SOLUTION**: https://github.com/MoonchildProductions/Pale-Moon/commit/6d773b16968b50c848083382b03bd99727c08f41
- [ ] Some Firefox directories are still being created  https://github.com/MrAlex94/Waterfox/issues/405
- [ ] webRequest leak  https://github.com/MrAlex94/Waterfox/issues/414 | **POSSIBLE SOLUTIONS** | https://reviewboard.mozilla.org/r/237446/diff/7#index_header | https://hg.mozilla.org/mozilla-central/rev/ad061f4fec73#l2.75
- [ ] Waterfox "remembers" screensize tiling wm https://github.com/MrAlex94/Waterfox/issues/527
- [ ] Silently installed Mozilla add-ons | https://github.com/MrAlex94/Waterfox/issues/515
- [ ] Checkbox and radio pixelated when zoomed in https://github.com/MrAlex94/Waterfox/issues/433
- [ ] `Mozilla has caught an Obj-C exception [NSInvalidArgumentException: -[NSImage drawInRect:]: unrecognized selector sent to instance 0x136655880]`
- [ ] Plugin-container crash on macOS < 10.9
- [ ] Update H.264 profiles decoder
- [ ] 1580288 (Classic)
- [ ] 1560667 (Classic)
- [ ] 1218456 (Can be done, need time!) https://github.com/classilla/tenfourfox/commit/5e0cd430c22a7e93294c3b281d6893e17b1195fc#diff-f3f6fe3abe7e7f0ee20bf4addb9e6bb7
- [ ] 1575934 (Update IPC for this?)
- [ ] https://reddit.com/r/waterfox/comments/dorwpc/cannot_log_into_my_bank_account_with_new_waterfox/
- [ ] Add YouTube override
- [ ] Update NSS library to esr60 + security patches from esr68

### Waterfox Current

- [x] Separate out australis theme
- [x] Fix loading of all NPAPI plugins

### Features to keep
Issues that are planning to be deprecated by Mozilla, but will be kept by Waterfox

- [ ] https://bugzilla.mozilla.org/show_bug.cgi?id=1589607

**ALREADY FIXED / NOT AN ISSUE ANYMORE:**

- [x] Global menu patch fails to merge https://github.com/MrAlex94/Waterfox/issues/350
- [x] Resource leak https://github.com/MrAlex94/Waterfox/issues/235
- [x] Zoom-in and Zoom-out cursors don't display https://github.com/MrAlex94/Waterfox/issues/347
- [x] Native ALSA support https://github.com/MrAlex94/Waterfox/issues/464
- [x] Dark theme issue with blue URL text https://github.com/MrAlex94/Waterfox/issues/282
- [x] Invisible scrollbars on macOS 10.13 High Sierra https://github.com/MrAlex94/Waterfox/issues/482
- [x] Memory issues, tabs getting delazified https://github.com/MrAlex94/Waterfox/issues/423
- [x] Customize not working https://github.com/MrAlex94/Waterfox/issues/416
- [x] Bookmarks followed by separators lose descriptions upon HTML import #564 
- [x] Ubuntu 17.04 mozconfig redirection error https://github.com/MrAlex94/Waterfox/issues/227
- [x] Global menu patch fails to merge https://github.com/MrAlex94/Waterfox/issues/350
- [x] Plugin update check no longer brings up any results https://github.com/MrAlex94/Waterfox/issues/357

**Comment by laniakea64** [comment]
> Don't expose navigator.AddonManager to content
> -> #204

https://github.com/MrAlex94/Waterfox/pull/449

**Comment by Peacock365** [comment]
@laniakea64 

> #449 

Scratched from the list. What about the rest?

**Comment by laniakea64** [comment]
idk about all of the rest.  The ones I reported are still unresolved, the resource URI leak is still unresolved, and I think most of the others are still unresolved too.

Not sure about this one though -
> Ubuntu 17.04 mozconfig redirection error
> -> #227

Will comment in that issue.

**Comment by MrAlex94** [comment]
Thanks for this list - it's actually quite helpful. I've started going through all the issues and patching them. If you guys can do local builds as well to test I'm not breaking anything, that would be appreciated 😄. I've been doing them myself and they're fine, but that's not too great of a test range as there are so many different configurations out in the wild.

**Comment by laniakea64** [comment]
@Peacock365 Should https://github.com/MrAlex94/Waterfox/issues/534 be added to this list?

**Comment by Peacock365** [comment]
Thanks for working on the regressions, @MrAlex94 

#404 doesn't seem to be fixable without major code rewrites, I have noticed. Even the current Firefox at times still has this problem.

#416 seems to be fixable via https://github.com/mozilla/gecko-dev/commit/6b36043a0db3

#422 seems to be fixable via https://github.com/MoonchildProductions/Pale-Moon/commit/6d773b16968b50c848083382b03bd99727c08f41

**Comment by laniakea64** [comment]
> URGENT!!!!!!! Resource leak
> -> #235

Seems fixed in self build from https://github.com/MrAlex94/Waterfox/commit/d5c25411b0838a4578f8a96aa2e09568d900e9b6 👍 

> Zoom-in/Zoom-out mouse cursors don't display
> -> #347

Fixed by https://github.com/MrAlex94/Waterfox/commit/d5c25411b0838a4578f8a96aa2e09568d900e9b6

**Comment by Peacock365** [comment]
@laniakea64 

I updated the list to reflect the fixes for #235 and #347 Thanks for the update.

#464 and #282 and #482 seem fixed, too.

**Comment by grahamperrin** [comment]
[Adobe Flash Player 28.0.0.126 can not present its context menu, crashes, with Waterfox 56.0.1 on Linux · Issue #335 …](https://github.com/MrAlex94/Waterfox/issues/335)

I could probably add a few more – I occasionally review [issues in chronological order](https://github.com/MrAlex94/Waterfox/issues?q=is%3Aissue+is%3Aopen+sort%3Acreated-asc), or least recently updated – but I'm wary of this issue becoming too long (for me) to absorb. YMMV

**Comment by grahamperrin** [comment]
> …  local builds as well to test I'm not breaking anything, …

Linux users: how are builds for you? 

(On FreeBSD-CURRENT, an attempt to build 56.1.0_18 fails at [audio/alsa-lib](https://www.freshports.org/audio/alsa-lib) 1.1.2_1. I <strike>can probably </strike> _might_ work around it reasonably easily (https://redd.it/8gk2v3), I don't know whether things will be as easy in Linux environments.)

**Comment by laniakea64** [comment]
> Linux users: how are builds for you?

Working well for me.

**Comment by Peacock365** [comment]
@laniakea64 

Would it be possible to create commits for the two issues I pointed to above the first @grahamperrin comment? After all, the code that fixes these is already out there (I linked to it in both cases)...

**Comment by laniakea64** [comment]
I don't have time to do more pull requests atm and I'm likely not the right person to do those anyway.  #166 is Windows-specific and I only have Linux; I can't reproduce #416; and I don't understand the code related to #422 well enough.

**Comment by Peacock365** [comment]
@MrAlex94 

Here is the list of known fixes again (so that it does not get buried in the thread):

#416 can be fixed via https://github.com/mozilla/gecko-dev/commit/6b36043a0db3 (see also @jbeich comment in the issue)

#422 can be fixed via https://github.com/MoonchildProductions/Pale-Moon/commit/6d773b16968b50c848083382b03bd99727c08f41

#350 can be fixed via https://bazaar.launchpad.net/%7Emozillateam/firefox/firefox.trusty/view/1200/debian/patches/unity-menubar.patch

#414 can be fixed via:
- https://reviewboard.mozilla.org/r/237446/diff/7#index_header
- https://hg.mozilla.org/mozilla-central/rev/ad061f4fec73#l2.75

#515 can be fixed via:

_devtools.webide.enabled_ - **false**
_devtools.webide.autoinstallADBHelper_ - **false**
_devtools.webide.autoinstallFxdtAdapters_ - **false**
_devtools.webide.autoConnectRuntime_ - **false**

#387 and #405 seem like trivial, cosmetical fixes.

**Comment by MrAlex94** [comment]
#166 won't be fixed with just that patch. And regardless, just reverting one patch when a whole lot has changed in the Chromium IPC is such a terrible idea. I'm not sure at this stage if it's worth supporting Vista or lower, as Mozilla have made good performance and security updates due to removing legacy support for those platforms.

#350 isn't going to be merged in. Isn't Unity effectively abandoned since the release of Ubuntu 18.04 LTS?

**Comment by Peacock365** [comment]
Well, in this case I think you can close issue #166 ... I see your reasoning for this one.

With #350 I wouldn't be so sure, as two older LTS versions are still supported and as all versions prior to Ubuntu 18.04 had unity. It's up to you, but I don't really see a reason here not to merge it. Let's not forget that Ubuntu 16.04 will receive updates until 2021, so it is well worth to patch the issue for that version alone.

Anyway, I hope the rest is helpful regardless.

**Comment by grahamperrin** [comment]
> -> #357

Duplicate of [about:addons 'Check to see if your plugins are up to date' · Issue #336 …](https://github.com/MrAlex94/Waterfox/issues/336)

**Comment by Peacock365** [comment]
I just noticed that @MrAlex94 mentioned additional bugs that he wanted to fix here:

https://blog.waterfoxproject.org/waterfox-56.0-release-download (Under "_What's due in Q1 2018?_")

Well, I have found a potential fix for the XML Buffer Overflow Crash (_Bug 485941_):
-> https://bugzilla.mozilla.org/show_bug.cgi?id=485941
-> **FIX:** https://bugzilla.mozilla.org/attachment.cgi?id=8901555&action=diff

Furthermore, @MrAlex94 mentioned _Bug 895096_ (inconsistent widths of border-collapsed table borders), for this one there are fixes as well:
-> https://bugzilla.mozilla.org/show_bug.cgi?id=895096
-> **FIXES:**
- https://hg.mozilla.org/mozilla-central/rev/5d6a0d528af1
- https://hg.mozilla.org/mozilla-central/rev/78e432e75482
- https://hg.mozilla.org/mozilla-central/rev/405957d41476

A font settings issue was brought up here:
-> https://www.reddit.com/r/waterfox/comments/7q50r9/it_seems_like_font_settings_are_erroneously/?st=JCQZQ5DB&sh=fb9aa53a
This thread suggested the following bug as the culprit, but this is **somewhat wrong** (this bug was fixed in Firefox / Waterfox 41.0):
https://bugzilla.mozilla.org/show_bug.cgi?id=789788
Instead, the **culprit** seems to be this bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1430798
_Bug 1430798_ seems to be related to something being mishandled by the fix for _Bug 789788_ though. See Jonathan Kew's reply in _Bug 1430798_ for more info.

**Comment by grahamperrin** [comment]
👍 

https://github.com/MrAlex94/Waterfox/issues/121#issue-213710186 drew attention to two more Mozilla bugs: 

- [1241717 - Linear gradient color shifts are not as expected when opacity changes (want gradients to interpolate in non-premultiplied colors, contrary to spec)](https://bugzilla.mozilla.org/show_bug.cgi?id=1241717)
- [1242145 - Diagonal checkerboard (CSS) rendering issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1242145)

… no fixes, though (unless I'm missing something).

**Comment by Peacock365** [comment]
@grahamperrin 

You missed something.

This deals with _Bug 1241717_:
https://github.com/MoonchildProductions/Pale-Moon/issues/308
These commits would **FIX** the issue:
- https://github.com/MoonchildProductions/Pale-Moon/commit/665ce3a5f1814c98bcd05f5611d1079ab99fd5d1
- https://github.com/MoonchildProductions/Pale-Moon/commit/dab2fee747d1853d5e081f69750869d45b7cf6b0

Mr. Straver hinted...
https://bugzilla.mozilla.org/show_bug.cgi?id=1242145#c10
...to this, which would fix _Bug 1242145_ when applied on top of the two aforementioned FIXES:
https://bugzilla.mozilla.org/show_bug.cgi?id=1241717#c10

**Comment by MrAlex94** [comment]
So I'm focusing on getting all the security patches done, then will revisit this after.

**Comment by Peacock365** [comment]
#433 is fixed. **EDIT:** Fix reverted as insufficient.

**Comment by criztovyl** [comment]
Could you maybe add a checklist to the issue description? That way it might be easier to track the status how many issues are already resolved. :)
(See [GitHub Help: About task lists](https://help.github.com/articles/about-task-lists/))

**Comment by grahamperrin** [comment]
Should I begin adding other open issues?

**Comment by Peacock365** [comment]
@criztovyl 

Sure, I did just set one up now.

@grahamperrin 

Feel free to do so. The two criterions I used to track "real" issues down are as follows:

1) The issue is not add-on related (in which case the add-on dev would be the one to approach).
2) The issue is present on a platform Waterfox actually supports (e.g. XP/Vista problems are WONTFIX by default).

I think those two criterions make sense. I am anticipating your further entries.

**Comment by criztovyl** [comment]
Thank you! :)

**Comment by grahamperrin** [comment]
OK, here goes. 

E&OE, and if you have any comment on an issue, please aim to make the comment _in_ the issue. 

Thanks …

**Comment by Peacock365** [comment]
#203 and #296 are duplicates, they also duplicate _Bug 606655_ mentioned here: https://blog.waterfoxproject.org/waterfox-56.0-release-download -> All this is going to be fixed once @MrAlex94 reintroduces the cookie prompt.

#411 is an intentional removal due to PIDs confusing some users. WONTFIX

#383 and #384 and #363 all deal with the same issue.

#370 is already fixed (the preference shows **true** again by default).

#399 and #400 are going to be fixed soon, and so is #548 as a whole. See Toromino's comment in #548. I am optimistic that a fitting patch will be surfacing soon.

#419 is fixed already, as the Waterfox 56.1 release notes state (WF 56.1 simultaneously fixes 10.8 of course): 
> OS X 10.7 support is now properly back. 

source: https://blog.waterfoxproject.org/waterfox-56.1.0-release-download

#380 could already have been fixed by Waterfox 56.1.0:
> You can now Refresh your profile at about:support!

source: https://blog.waterfoxproject.org/waterfox-56.1.0-release-download

#304 could be fixed by disabling Stylo on the platform. Possibly disabling it on OS X 10.8 as well.

#560 would require Firefox 57+ WebExtension APIs to be backported to Waterfox 56.

**Comment by grahamperrin** [comment]
Thanks, can you comment in issues? So that subscribers can be more immediately aware. 

NB I don't treat an issue as resolved whilst it's open. Some of the green badges above will turn red reasonably soon.

**Comment by grahamperrin** [comment]
@MrAlex94 re: your <https://github.com/MrAlex94/Waterfox/issues/538#event-1603332630> would you like this meta issue to also track **enhancement requests** (ERs) that <strike>are</strike> <strike>will be</strike> may be actionable? E.g. if people contribute PRs. 

I see the three that are labelled _enhancement_, plus probably one more.

**Comment by Peacock365** [comment]
@grahamperrin 

I can't speak for @MrAlex94 of course, yet personally I would refrain from doing so. Look at how little progress we have made here so far. I understand that @MrAlex94 has other important priorities (e.g. merging in security updates), but it is still beyond me how trivial fixes like those for #422, #564, #515 aren't merged in in a more timely manner. With all due respect.

**Comment by grahamperrin** [comment]
I viewed this list as primarily for _tracking_ …

… not for _prioritising_, although I understand why some people might want to use the list in that way. 

We have, for example, a non-bug issue that "is coming …" (is _unresolved_) but not yet listed. 

## Prioritising and scheduling

Ideals, in the context of GitHub, should be [labels](https://github.com/MrAlex94/Waterfox/labels) and [milestones](https://github.com/MrAlex94/Waterfox/milestones). 

I see good use of priority labels in repos such as Mozilla's _Activity Stream_. For example: 

- least priority (P4) https://github.com/mozilla/activity-stream/issues?q=label%3AP4+is%3Aclosed+sort%3Acomments-desc (closed, sorted by most commented)
- highest priority (P1) https://github.com/mozilla/activity-stream/issues?q=label%3AP1+is%3Aclosed+sort%3Acomments-desc (closed, sorted in the same way) – including a handful that were **critical**. 

Note, that's **not** to suggest that Alex should (or must) begin doing more with labels; 

>  if not very carefully planned – and if not applied with consistency – things such as labels can make it more difficult to find what's required, especially when a repository becomes relatively busy.

**Comment by ghost** [comment]
#357 was closed
but it's actually a duplicate of #336
(not tagged as duplicate)

#227 was closed

**Comment by grahamperrin** [comment]
[Can't access Google podcasts from Android Waterfox : waterfox](https://www.reddit.com/r/waterfox/comments/9yrg1t/cant_access_google_podcasts_from_android_waterfox/)

**Comment by grahamperrin** [comment]
[Bug; Waterfox 56.2.5 on OSX Mojave; File Save-As dialog freezes the app : waterfox](https://www.reddit.com/r/waterfox/comments/9ylnno/bug_waterfox_5625_on_osx_mojave_file_saveas/) with reference to: 

- Mozilla bug [1489785 - [MacOS 10.14] Cannot choose where to download files or print because popup window always freeze](https://bugzilla.mozilla.org/show_bug.cgi?id=1489785) 

>  VERIFIED FIXED in Firefox -esr60

**Comment by Squall-Leonhart** [comment]
issue #962  added for another webextension causing delazification issues in Waterfox

**Comment by mzso** [comment]
[**@Squall-Leonhart**](https://github.com/Squall-Leonhart) commented on [2019. máj. 12. 04:04 CEST](https://github.com/MrAlex94/Waterfox/issues/538#issuecomment-491558078 "2019-05-12T02:04:34Z - Replied by Github Reply Comments"):
> issue [#962](https://github.com/MrAlex94/Waterfox/issues/962) added for another webextension causing delazification issues in Waterfox

The MyJDownloader Browser Extension is also one of them.

**Comment by ilu33** [comment]
**Waterfox lacks obligatory legal information** #1021 needs to be added to this. It's such an easy fix to add the source link to about:buildconfig to comply with Mozillas license.

**Comment by troysjanda** [comment]
#1200 is still an issue with the 2019.10-1 current as well as last weeks 2019.10 current

**Comment by grahamperrin** [comment]
@troysjanda thanks, and https://github.com/MrAlex94/Waterfox/issues/538#issuecomment-389295921

> if you have any comment on an issue, please aim to make the comment _in_ the issue.

**Comment by MrAlex94** [comment]
Okay have updated the list and re-organised it a bit. Shame I can't take over issues so @Peacock365 doesn't get bombarded with notifications :-)

**Comment by troysjanda** [comment]
expect a new current build soon?

**Comment by grahamperrin** [comment]
https://www.waterfox.net/blog/waterfox-2019.12-release/ coming soon

**Comment by laniakea64** [comment]
Couple things to consider adding to the list of Waterfox Current specific issues? -

1) It is still impossible to do a stock Waterfox Current build on Linux.  I still use these mozconfig customisations to unbreak building - https://github.com/MrAlex94/Waterfox/issues/944#issuecomment-526942809

2) Quoting @Peacock365 -
> _security.family_safety.mode_ must be set to 0, in order to fend off potential issues due to local Man in the middle setups. See the Pale Moon 28.4.1 release notes, too: https://www.palemoon.org/releasenotes-archived.shtml Waterfox 56 had this set to 0 as well, as opposed to Firefox where this has been set to 2 since Firefox 52.


I'm not able to create pull requests for these issues, since:
 - regarding (1), I have no way to tell whether any fix I use would be too specific to my build environment,
 - regarding (2), although I do see that pref at default value of `2`, I'm on Linux and that only applies to Windows.

**Comment by MrAlex94** [comment]
> Couple things to consider adding to the list of Waterfox Current specific issues? -
> 
>     1. It is still impossible to do a stock Waterfox Current build on Linux.  I still use these mozconfig customisations to unbreak building - [#944 (comment)](https://github.com/MrAlex94/Waterfox/issues/944#issuecomment-526942809)
> 
>     2. Quoting @Peacock365 -
> 
> 
> > _security.family_safety.mode_ must be set to 0, in order to fend off potential issues due to local Man in the middle setups. See the Pale Moon 28.4.1 release notes, too: https://www.palemoon.org/releasenotes-archived.shtml Waterfox 56 had this set to 0 as well, as opposed to Firefox where this has been set to 2 since Firefox 52.
> 
> I'm not able to create pull requests for these issues, since:
> 
>     * regarding (1), I have no way to tell whether any fix I use would be too specific to my build environment,
> 
>     * regarding (2), although I do see that pref at default value of `2`, I'm on Linux and that only applies to Windows.

Hmm, I can seem to build with the current .mozconfig, maybe I've got a local change or ENV variable set. I will double check

**Comment by troysjanda** [comment]
Curious, will there be a new Current build soon? Not being pushy just saw that Classic was updated but no Current build.

**Comment by MrAlex94** [comment]
This is issue has been closed and replaced with [this issue](https://github.com/MrAlex94/Waterfox/issues/1630), since GitHub does not allow changing ownership of issues.
