### ISSUE TITLE
56.2.8 pre-release checklist

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#882]
Maybe worth checking, testing, a few things – before release. Before distribution of any binary …

**Comment by grahamperrin** [comment]
### Version: user typos

- [x] observe the number `7` in the wrong place. 

This one is just for laughs, and it's more likely to happen _post_-release. 

With two `2`s and one `7`, and with `7` commonly associated with Firefox Quantum, sooner or later someone will mis-place the `7` after the `56.`… `:-)`

**Comment by grahamperrin** [comment]
### MFSA 2019-05

- [x] glancing at the commits on 2019-03-04, I assume that MFSA 2019-05 has been addressed. 

Related: 

1. https://redd.it/aq8fnv (2019-02-13)
2. https://redd.it/aqyq1w (2019-02-15)
3. https://www.reddit.com/comments/ay7cxv/-/ehyw0u5/ (2019-03-07)

**Comment by grahamperrin** [comment]
### craigslist

- [x] increased likelihood of the reply button working

This would be nice, and _might_ result from suitable changes to UA strings, but IMHO it's not a show-stopper. 

Related: 

- [Craiglist Reply button does not work on Waterfox but does on Firefox · Issue #861 …](https://github.com/MrAlex94/Waterfox/issues/861)

**Comment by grahamperrin** [comment]
### User agent strings

Retrospective: 

- [The Waterfox Blog | Waterfox 56.2.3 Release](https://blog.waterfoxproject.org/waterfox-56.2.3-release-download) – the mid-September 2018 changes
- changes for 56.2.7.1 were committed at https://github.com/MrAlex94/Waterfox/commit/9e082b706f4355e7deaa8c68ee2852529c55acfc and described at https://www.reddit.com/comments/9drjqx/-/efmyx9t/ 

- [ ] WhatsApp Web

https://www.reddit.com/comments/9drjqx/-/efm4pkk/ suggests `Mozilla/5.0 (rv:56.0) Gecko/20100101 Firefox/56.0` (essentially: 56 is greater than the 30 that's required by the service). 

https://www.reddit.com/comments/9drjqx/-/eguk8pw/?context=1 as I very strongly discourage "user-defined, non-default site-specific `general.useragent.override.…` strings", so I'm slightly wary of adding any WhatsApp-specific override to Waterfox. Sure, it could be a quick _partial_ fix (if we ignore the Service Worker aspect) but then WhatsApp Web might suddenly change (can't guess Facebook's plans for the service, so on). I'm probably too wary `:-/` just thinking aloud. 

https://twitter.com/grahamperrin/status/1094654582230339584 and https://twitter.com/grahamperrin/status/1104607644948541441 addressed WhatsApp. From the latter: 

> WhatsApp Web misinterprets Firefox 56-based Waterfox as inferior to Firefox 30. Please, can you fix the web app? Thanks. …

- [ ] YouTube

Re: <https://github.com/MrAlex94/Waterfox/issues/880#issuecomment-471753622>, <https://github.com/MrAlex94/Waterfox/issues/880#issuecomment-471869686> and <https://github.com/MrAlex94/Waterfox/commit/9e082b706f4355e7deaa8c68ee2852529c55acfc#diff-a633a6dfcf161bf7cb9d3d9cdcdc2faeR910>, it might be tempting to drop from `65.0` to `62.0` but for what it's worth, I'd like a pre-release test of `60.0`. 

60 because it's the Firefox ESR that's currently supported by Mozilla, and I assume that some sites will lazily accept this. Also because it's not _too_ far from 56 or 57. 

65 or 66 will be a spoof too far.

**Comment by Peacock365** [comment]
> ### Version: user typos
> * [ ]  observe the number `7` in the wrong place.
> 
> This one is just for laughs, and it's more likely to happen _post_-release.
> 
> With two `2`s and one `7`, and with `7` commonly associated with Firefox Quantum, sooner or later someone will mis-place the `7` after the `56.`… `:-)`

This commit fixes that:

https://github.com/MrAlex94/Waterfox/pull/886

Waiting for merge.

**Comment by grahamperrin** [comment]
### GitHub

- [x] paste image to commentary
- [x] preview commentary

Checked by me, post-release, with Waterfox 56.2.8 on Windows 7 Enterprise.

**Comment by MrAlex94** [comment]
Amazon Prime for example doesn’t with the UA set to v60

**Comment by grahamperrin** [comment]
Instead, maybe have overrides for e.g. Amazon Prime?

Gut feeling: defaulting to spoof Firefox 65.0 (or 66.0) might be risky, and not only for the known issue with GitHub. Any number of other sites might behave as if there's support for things that are not yet supported.

**Comment by MrAlex94** [comment]
Which GitHub issues?

**Comment by grahamperrin** [comment]
https://github.com/webcompat/web-bugs/issues/25578#issuecomment-464426795 with the tl;dr _probably PEBKAM_ in the subsequent comment, https://github.com/webcompat/web-bugs/issues/25578#issuecomment-464426979

**Comment by TheQuickFox** [comment]
https://github.com/MrAlex94/Waterfox/issues/738

is this one fixed now? It is still present in 56.2.7.1

**Comment by MrAlex94** [comment]
A lot of website issues have been fixed by enabling Web Components, which fixes GitHub issues mentioned in that thread.

**Comment by laniakea64** [comment]
@MrAlex94 Actually https://github.com/MrAlex94/Waterfox/commit/5cf66c33ededb7f186993201e2094d50021ed6e3 seems to break GitHub for me.  For example, it no longer shows relative times, e.g. for individual commits in https://github.com/MrAlex94/Waterfox/commits/master and in the lists of issues.

Setting both of those prefs to `false` gets it working again.

(I have a Firefox 60 UA override for GitHub.  I did try changing it to Firefox 65, but that didn't help.)

**Comment by MrAlex94** [comment]
Do you have any screenshots?

**Comment by laniakea64** [comment]
> Do you have any screenshots?

On list of Waterfox issues, sorted by most recently updated:

How it should look (taken with both Web Components prefs set to `false`) -
![Screen Shot 2019-03-13 1](https://user-images.githubusercontent.com/16628411/54320373-28fb2e00-45c3-11e9-987d-9d3c617d596c.png)

Broken page (taken with Web Components prefs reset to default value) -
![Screen Shot 2019-03-13 2](https://user-images.githubusercontent.com/16628411/54320397-3e705800-45c3-11e9-94aa-855247239d05.png)

Notice that in the first screenshot, GitHub shows how many minutes/hours/days ago each issue was updated, whereas in the broken one you only see the date.

**Comment by MrAlex94** [comment]
Your GitHub looks different to mine, with or without web components enabled look like:

![Screenshot](https://i.imgur.com/DxFJHXN.png)

Regardless of anything cosmetic, is anything actually not working?

**Comment by laniakea64** [comment]
> Your GitHub looks different to mine,

We're looking at different pages.  The screenshots are of https://github.com/MrAlex94/Waterfox/issues?q=sort%3Aupdated-desc

> Regardless of anything cosmetic, is anything actually not working?

Yes, some more examples:

 - Toolbar buttons above this commenting textbox don't do anything
 - Comment edit history just spins endlessly, never loads
 - Copying clone URL to clipboard using GitHub's button for that, doesn't work
 - Copying the link of an individual issue comment using triple dot > Copy Link doesn't work
 - When clicking "New Issue" when not signed in, the "X" that's supposed to close the overlay doesn't do anything

And as with the relative time feature, setting the two Web Components prefs to `false` gets all these features working again.

(BTW, in my experience, the relative date feature is a canary in the coal mine for GitHub being significantly broken.)

**Comment by grahamperrin** [comment]
Re: https://github.com/MrAlex94/Waterfox/issues/871#issuecomment-472649999 @MrAlex94 hmm, I hesitate because (OT from reCAPTCHA) I seem to be **not** within any affected subset of users of YouTube e.g. https://redd.it/amsugb … https://redd.it/ayjop0 and https://github.com/MrAlex94/Waterfox/issues/880#issuecomment-472571133 (I mean: without reproducing the issue, I/we can't test the effectiveness of a change of UA). 

For _pre-release_ test purposes I still lean towards Firefox ESR ~60 and (back to #871 where I'll continue testing against the reCAPTCHA demo) it _might_ be OK to retain `Waterfox` in the UA strings – with some exceptions, which I'll add to the checklist, although I shouldn't make it _too_ long a list :-)

Side note: #871 might have been worked around much sooner if I had not been thrown off-scent by the peculiar behaviour with Firefox 65 on Tier-3 FreeBSD-CURRENT.

**Comment by grahamperrin** [comment]
### ITV Hub

- [ ] episode https://www.itv.com/hub/vera/1a7314a0008

Notes: 

- the episode originally linked from https://www.reddit.com/comments/aog4s5/-/eg14e2p/ is no longer available
- probable keywords _DRM_, _Widevine_
- I assume that content will be restricted e.g. UK
- IMHO not a show-stopper.

**Comment by MrAlex94** [comment]
> > Your GitHub looks different to mine,
> 
> We're looking at different pages. The screenshots are of https://github.com/MrAlex94/Waterfox/issues?q=sort%3Aupdated-desc
> 
> > Regardless of anything cosmetic, is anything actually not working?
> 
> Yes, some more examples:
> 
>     * Toolbar buttons above this commenting textbox don't do anything
> 
>     * Comment edit history just spins endlessly, never loads
> 
>     * Copying clone URL to clipboard using GitHub's button for that, doesn't work
> 
>     * Copying the link of an individual issue comment using triple dot > Copy Link doesn't work
> 
>     * When clicking "New Issue" when not signed in, the "X" that's supposed to close the overlay doesn't do anything
> 
> 
> And as with the relative time feature, setting the two Web Components prefs to `false` gets all these features working again.
> 
> (BTW, in my experience, the relative date feature is a canary in the coal mine for GitHub being significantly broken.)

Okay verified! Will flip-flop some more on the UA, probably switch to mimic ESR60 and disable WebComponents.

**Comment by grahamperrin** [comment]
### Amazon Prime

I'm not a subscriber but re: <https://github.com/MrAlex94/Waterfox/issues/882#issuecomment-472544760> above, let's have at least one Amazon video on the checklist. Here's one for a video that I own: 

- [x] https://www.amazon.co.uk/gp/video/detail/B00X674KKU/ref=atv_dp_pb_core?autoplay=1&t=0 ▶ <strike>aim for the trailer</strike>

Checked by me, post-release, with Waterfox 56.2.8 on Windows 7 Enterprise.

**Postscript, 2019-11-03**: no, **NOT** the trailer! The trailer is not subject to DRM. 

### Netflix

Again, I'm not a subscriber but here's one: 

- [ ] https://www.netflix.com/watch/80170280

- taken from https://github.com/MrAlex94/Waterfox/issues/316#issuecomment-385166757

**Comment by grahamperrin** [comment]
https://redd.it/b0uvxj noted with thanks. 

https://matrix.to/#/!hfjizCHuzXdRbJxoAj:matrix.org/$15525478201099677lbxxg:matrix.org?via=matrix.org folks are welcome to either: 

- join me in this quiet room; or 
- take a read-only view, without participating (the **Access message** link in the **Matrix-Static** row)

– I'll share test results.

**Comment by laniakea64** [comment]
> https://redd.it/b0uvxj noted with thanks.

@MrAlex94 I realise 56.2.8 has already been tagged, but https://github.com/MrAlex94/Waterfox/pull/888 needs to be addressed before tomorrow's release.

**Comment by grahamperrin** [comment]
Distribution has begun. 

I'll close this issue, then check (tick) some of the boxes above if/when confirmation of completeness comes from end users. 

WhatsApp Web will probably remain non-checked (a documentation issue). 

Similarly we may receive problem reports from some users of web applications such as Gmail – possible problems where a service worker was gained (and not manually un-registered, and not subsequently blocked) prior to 56.2.8. 

----

OT (I'll raise a question elsewhere) I can't build 56.2.8 on FreeBSD-CURRENT. 

By adopting some 56.2.8-oriented preferences in ~56.2.7.1, I did find time to quickly check these two before I realised that distribution had begun: 

- [x] https://cosmicshambles.com/ – taken from https://www.reddit.com/comments/9drjqx/-/ecgcug6/
- [x] https://volunteerlogin.org/chat/index.php – taken from https://www.reddit.com/comments/9drjqx/-/eftbdao/

I also tested UA strings that were _similar to_ the strings that were ultimately chosen for 56.2.8, I should tentatively treat these as checked: 

- [x] craigslist reply buttons https://github.com/MrAlex94/Waterfox/issues/861#issuecomment-472624537
- [x] reCAPTCHA in general https://github.com/MrAlex94/Waterfox/issues/871#issuecomment-472649814

**Comment by grahamperrin** [comment]
> … enabling Web Components, …

For future reference, another barometer might be: 

- <https://demo.home-assistant.io/>

Context: [Home Assistant compatibility with Waterfox · Issue #2778 · home-assistant/home-assistant-polymer](https://github.com/home-assistant/home-assistant-polymer/issues/2778) in particular, <https://github.com/home-assistant/home-assistant-polymer/issues/2778#issuecomment-464504641>: 

>> … Firefox 60 ESR … 

>> … Even after turn on the options, it still won't work. The icon image is not in correct position therefore the UI is unusable.
